const PORTFOLIO_DATA = [
  {
    "slug": "2r-art-collective",
    "type": "initiative",
    "file": "initiatives/2r-art-collective.md",
    "title": "2R Art Collective",
    "description": "Second Renaissance art collective for artistic collaboration and cultural production.",
    "status": "active",
    "category": null,
    "created": "Fri Apr 10 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "second-renaissance",
      "art"
    ],
    "url": "https://secondrenaissance.net/art/collective",
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "sylvie-barbier",
    "sitePath": "/initiatives/2r-art-collective"
  },
  {
    "slug": "2r-festival",
    "type": "initiative",
    "file": "initiatives/2r-festival.md",
    "title": "2R Festival",
    "description": "The Second Renaissance Festival — a flagship gathering celebrating the emerging Second Renaissance.",
    "status": "paused",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "gatherings",
    "tags": [
      "second-renaissance",
      "community",
      "events"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "sylvie-barbier",
    "sitePath": "/initiatives/2r-festival"
  },
  {
    "slug": "2rcon",
    "type": "initiative",
    "file": "initiatives/2rcon.md",
    "title": "2RCon",
    "description": "Second Renaissance related conference initiative.",
    "status": "paused",
    "category": null,
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "lifeitself",
      "conference",
      "second-renaissance"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/2rcon"
  },
  {
    "slug": "ai-sense-making",
    "type": "initiative",
    "file": "initiatives/ai-sense-making.md",
    "title": "AI Sense-Making",
    "description": "Inquiry into the epistemic, social, and civilisational implications of AI.",
    "status": "idea",
    "category": null,
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself-research",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/ai-sense-making"
  },
  {
    "slug": "archipelago-place",
    "type": "initiative",
    "file": "initiatives/archipelago-place.md",
    "title": "Archipelago.place",
    "description": "Platform concept for mapping and connecting distributed places, hubs, and communities.",
    "status": "active",
    "category": null,
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "developmental-spaces-dds",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/archipelago-place"
  },
  {
    "slug": "collective-action-course",
    "type": "initiative",
    "file": "initiatives/collective-action-course.md",
    "title": "Collective Action Course",
    "description": "Course on coordination, shared identity, and the cultural foundations of collective action.",
    "status": "idea",
    "category": null,
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself-research",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/collective-action-course"
  },
  {
    "slug": "comms",
    "type": "initiative",
    "file": "initiatives/comms.md",
    "title": "Comms",
    "description": "Umbrella initiative for Life Itself communications work across newsletter, podcast, and short-form media.",
    "status": "active",
    "category": "grouping",
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "communications",
      "media"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "yoyo-pasieka",
    "sitePath": "/initiatives/comms"
  },
  {
    "slug": "community",
    "type": "initiative",
    "file": "initiatives/community.md",
    "title": "Community",
    "description": "Life Itself community building — online presence and in-person gatherings.",
    "status": "active",
    "category": "grouping",
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "community"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "armelle-boussidan",
    "sitePath": "/initiatives/community"
  },
  {
    "slug": "conscious-careers-guide",
    "type": "initiative",
    "file": "initiatives/conscious-careers-guide.md",
    "title": "Conscious Careers Guide",
    "description": "Life Itself related guide initiative around conscious careers.",
    "status": "idea",
    "category": null,
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself-courses",
    "tags": [
      "lifeitself",
      "guide",
      "careers"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": null,
    "sitePath": "/initiatives/conscious-careers-guide"
  },
  {
    "slug": "conscious-coliving-courses",
    "type": "initiative",
    "file": "initiatives/conscious-coliving-courses.md",
    "title": "Conscious Coliving Courses",
    "description": "Courses on conscious co-living practice and design.",
    "status": "maintenance",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "conscious-coliving",
    "tags": [
      "developmental-spaces",
      "conscious-coliving",
      "courses"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/conscious-coliving-courses"
  },
  {
    "slug": "conscious-coliving",
    "type": "initiative",
    "file": "initiatives/conscious-coliving.md",
    "title": "Conscious Co-living",
    "description": "The consciouscoliving.org website and initiative — resources and community around conscious co-living.",
    "status": "maintenance",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "developmental-spaces-dds",
    "tags": [
      "developmental-spaces",
      "conscious-coliving"
    ],
    "url": "https://consciouscoliving.org",
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/conscious-coliving"
  },
  {
    "slug": "developmental-spaces-dds",
    "type": "initiative",
    "file": "initiatives/developmental-spaces-dds.md",
    "title": "Developmental Spaces (DDS)",
    "description": "Deliberately developmental / neo-monastic spaces for sustained inner and collective development.",
    "status": "active",
    "category": null,
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/developmental-spaces-dds"
  },
  {
    "slug": "developmental-spaces-infrastructure",
    "type": "initiative",
    "file": "initiatives/developmental-spaces-infrastructure.md",
    "title": "DS Infrastructure",
    "description": "Basic infrastructure and content for the Developmental Spaces initiative.",
    "status": "maintenance",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "developmental-spaces-dds",
    "tags": [
      "developmental-spaces",
      "infrastructure"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/developmental-spaces-infrastructure"
  },
  {
    "slug": "developmental-spaces-network",
    "type": "initiative",
    "file": "initiatives/developmental-spaces-network.md",
    "title": "DS Network",
    "description": "Network of deliberately developmental spaces and the people and organisations building them.",
    "status": "maintenance",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "developmental-spaces-dds",
    "tags": [
      "developmental-spaces",
      "network"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/developmental-spaces-network"
  },
  {
    "slug": "farmhouse-hub",
    "type": "initiative",
    "file": "initiatives/farmhouse-hub.md",
    "title": "Farmhouse Hub",
    "description": "Ongoing maintenance and development of the farmhouse hub.",
    "status": "active",
    "category": null,
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself-hubs",
    "tags": [
      "lifeitself",
      "hubs",
      "place"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "armelle-boussidan",
    "sitePath": "/initiatives/farmhouse-hub"
  },
  {
    "slug": "felix-hub",
    "type": "initiative",
    "file": "initiatives/felix-hub.md",
    "title": "Felix Hub",
    "description": "The Felix Hub, a Life Itself residential community space.",
    "status": "idea",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself-hubs",
    "tags": [
      "lifeitself",
      "hubs",
      "place"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "manon-kersten",
    "sitePath": "/initiatives/felix-hub"
  },
  {
    "slug": "gatherings",
    "type": "initiative",
    "file": "initiatives/gatherings.md",
    "title": "Gatherings",
    "description": "In-person gatherings and events for the Life Itself and Second Renaissance community.",
    "status": "paused",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "community",
    "tags": [
      "lifeitself",
      "community",
      "events"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/gatherings"
  },
  {
    "slug": "life-guild",
    "type": "initiative",
    "file": "initiatives/life-guild.md",
    "title": "Life Guild",
    "description": "Life Itself sub-initiative around guild or community formation.",
    "status": "maintenance",
    "category": null,
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "lifeitself",
      "community"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/life-guild"
  },
  {
    "slug": "life-itself-courses",
    "type": "initiative",
    "file": "initiatives/life-itself-courses.md",
    "title": "Life Itself Courses",
    "description": "Umbrella initiative for course-related work within Life Itself.",
    "status": "active",
    "category": "grouping",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "courses"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": null,
    "sitePath": "/initiatives/life-itself-courses"
  },
  {
    "slug": "life-itself-hubs",
    "type": "initiative",
    "file": "initiatives/life-itself-hubs.md",
    "title": "Life Itself Hubs",
    "description": "Residential conscious communities and hubs within the broader Life Itself ecosystem.",
    "status": "active",
    "category": "grouping",
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "hubs",
      "community"
    ],
    "url": "https://lifeiteself.org/hubs",
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "matthew-de-caussin",
    "sitePath": "/initiatives/life-itself-hubs"
  },
  {
    "slug": "life-itself-management",
    "type": "initiative",
    "file": "initiatives/life-itself-management.md",
    "title": "Life Itself Management",
    "description": "Ongoing management and coordination work for Life Itself.",
    "status": "active",
    "category": "grouping",
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "management"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "matthew-de-caussin",
    "sitePath": "/initiatives/life-itself-management"
  },
  {
    "slug": "life-itself-newsletter",
    "type": "initiative",
    "file": "initiatives/life-itself-newsletter.md",
    "title": "Life Itself Newsletter",
    "description": "Newsletter initiative for Life Itself communications and updates.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "comms",
    "tags": [
      "lifeitself",
      "communications",
      "newsletter",
      "media"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "yoyo-pasieka",
    "sitePath": "/initiatives/life-itself-newsletter"
  },
  {
    "slug": "life-itself-podcast",
    "type": "initiative",
    "file": "initiatives/life-itself-podcast.md",
    "title": "Life Itself Podcast",
    "description": "Podcast initiative under Life Itself.",
    "status": "maintenance",
    "category": null,
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "comms",
    "tags": [
      "lifeitself",
      "podcast"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "jarlath-rice",
    "sitePath": "/initiatives/life-itself-podcast"
  },
  {
    "slug": "life-itself-practicum",
    "type": "initiative",
    "file": "initiatives/life-itself-practicum.md",
    "title": "Life Itself Practicum",
    "description": "A practicum of service, learning, and community living within Life Itself.",
    "status": "paused",
    "category": null,
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself-courses",
    "tags": [
      "lifeitself",
      "practicum",
      "learning"
    ],
    "url": "https://news.lifeitself.org/p/life-itself-practicum-autumn-2025",
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": null,
    "sitePath": "/initiatives/life-itself-practicum"
  },
  {
    "slug": "life-itself-research",
    "type": "initiative",
    "file": "initiatives/life-itself-research.md",
    "title": "Life Itself Research",
    "description": "Research initiatives within Life Itself, including inquiry into civilisational change, AI, and related topics.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "research"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/life-itself-research"
  },
  {
    "slug": "life-itself-strategy",
    "type": "initiative",
    "file": "initiatives/life-itself-strategy.md",
    "title": "Life Itself Strategy",
    "description": "Developing, presenting and maintaining the Life Itself strategy.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself-management",
    "tags": [
      "lifeitself",
      "strategy"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/life-itself-strategy"
  },
  {
    "slug": "life-itself-websites",
    "type": "initiative",
    "file": "initiatives/life-itself-websites.md",
    "title": "Life Itself Websites",
    "description": "Life Itself web presence including the main site and subsites.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "comms",
    "tags": [
      "lifeitself",
      "website",
      "communications"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/life-itself-websites"
  },
  {
    "slug": "life-itself",
    "type": "initiative",
    "file": "initiatives/life-itself.md",
    "title": "Life Itself",
    "description": "Core umbrella project encompassing vision, hubs, research, practice, and digital presence for wiser societies.",
    "status": "active",
    "category": "grouping",
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": null,
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/life-itself"
  },
  {
    "slug": "local-groups",
    "type": "initiative",
    "file": "initiatives/local-groups.md",
    "title": "Local Groups",
    "description": "Life Itself local groups around the world — self-organised community nodes.",
    "status": "active",
    "category": null,
    "created": "Fri Apr 24 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "community",
    "tags": [
      "lifeitself",
      "community",
      "local-groups"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/local-groups"
  },
  {
    "slug": "online-community",
    "type": "initiative",
    "file": "initiatives/online-community.md",
    "title": "Online Community",
    "description": "WhatsApp groups-based online community for Life Itself members and the broader Second Renaissance network.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "community",
    "tags": [
      "lifeitself",
      "community",
      "online"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "armelle-boussidan",
    "sitePath": "/initiatives/online-community"
  },
  {
    "slug": "online-shop",
    "type": "initiative",
    "file": "initiatives/online-shop.md",
    "title": "Online Shop",
    "description": "Potential online shop for Life Itself and related initiatives.",
    "status": "idea",
    "category": null,
    "created": "Fri Apr 10 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself",
    "tags": [
      "commerce"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/online-shop"
  },
  {
    "slug": "ops",
    "type": "initiative",
    "file": "initiatives/ops.md",
    "title": "Ops",
    "description": "Operational work and coordination for Life Itself.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself-management",
    "tags": [
      "lifeitself",
      "operations"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "matthew-de-caussin",
    "sitePath": "/initiatives/ops"
  },
  {
    "slug": "over-the-mountains",
    "type": "initiative",
    "file": "initiatives/over-the-mountains.md",
    "title": "Over the Mountains",
    "description": "Blog and podcast exploring civilisational renewal and the emerging Second Renaissance.",
    "status": "active",
    "category": null,
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "lifeitself",
      "writing",
      "podcast"
    ],
    "url": "https://overthemountains.substack.com",
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "jarlath-rice",
    "sitePath": "/initiatives/over-the-mountains"
  },
  {
    "slug": "praxis-ecology",
    "type": "initiative",
    "file": "initiatives/praxis-ecology.md",
    "title": "Praxis Ecology",
    "description": "Initiative for Praxis Ecology learning and course development.",
    "status": "active",
    "category": null,
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself-courses",
    "tags": [
      "lifeitself",
      "course",
      "learning"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "valerie-duvauchelle",
    "sitePath": "/initiatives/praxis-ecology"
  },
  {
    "slug": "riverside-hub",
    "type": "initiative",
    "file": "initiatives/riverside-hub.md",
    "title": "Riverside Hub",
    "description": "The Riverside Hub, a Life Itself residential community space.",
    "status": "paused",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "life-itself-hubs",
    "tags": [
      "lifeitself",
      "hubs",
      "place"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/riverside-hub"
  },
  {
    "slug": "second-renaissance-book",
    "type": "initiative",
    "file": "initiatives/second-renaissance-book.md",
    "title": "Second Renaissance Book",
    "description": "A book articulating the Second Renaissance vision and ideas.",
    "status": "active",
    "category": null,
    "created": "Tue Apr 21 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "second-renaissance",
      "writing",
      "product"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/second-renaissance-book"
  },
  {
    "slug": "second-renaissance-community-calls",
    "type": "initiative",
    "file": "initiatives/second-renaissance-community-calls.md",
    "title": "2R Community Calls",
    "description": "Regular community calls for the Second Renaissance initiative.",
    "status": "paused",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "second-renaissance",
      "community"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": null,
    "sitePath": "/initiatives/second-renaissance-community-calls"
  },
  {
    "slug": "second-renaissance-course",
    "type": "initiative",
    "file": "initiatives/second-renaissance-course.md",
    "title": "2R Course",
    "description": "Course programme for the Second Renaissance initiative, including the Explorer course series.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance-courses",
    "tags": [
      "second-renaissance",
      "courses"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/second-renaissance-course"
  },
  {
    "slug": "second-renaissance-courses",
    "type": "initiative",
    "file": "initiatives/second-renaissance-courses.md",
    "title": "Second Renaissance Courses",
    "description": "Umbrella grouping for course-related work within the Second Renaissance initiative.",
    "status": "active",
    "category": "grouping",
    "created": "Tue May 12 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "second-renaissance",
      "courses"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": null,
    "sitePath": "/initiatives/second-renaissance-courses"
  },
  {
    "slug": "second-renaissance-magazine",
    "type": "initiative",
    "file": "initiatives/second-renaissance-magazine.md",
    "title": "2R Magazine",
    "description": "A magazine exploring and expressing the ideas and culture of the Second Renaissance.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "second-renaissance",
      "media",
      "publishing"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "sylvie-barbier",
    "sitePath": "/initiatives/second-renaissance-magazine"
  },
  {
    "slug": "second-renaissance-newsletter",
    "type": "initiative",
    "file": "initiatives/second-renaissance-newsletter.md",
    "title": "2R Newsletter",
    "description": "Newsletter for the Second Renaissance initiative.",
    "status": "paused",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "second-renaissance",
    "tags": [
      "second-renaissance",
      "communications"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "yoyo-pasieka",
    "sitePath": "/initiatives/second-renaissance-newsletter"
  },
  {
    "slug": "second-renaissance",
    "type": "initiative",
    "file": "initiatives/second-renaissance.md",
    "title": "Second Renaissance",
    "description": "Cultural-civilisational renewal project including narrative, events, and movement-building.",
    "status": "active",
    "category": null,
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/second-renaissance"
  },
  {
    "slug": "sensemaking-studio",
    "type": "initiative",
    "file": "initiatives/sensemaking-studio.md",
    "title": "Sensemaking Studio",
    "description": "Consulting offering for sensemaking, strategy, and related advisory work.",
    "status": "paused",
    "category": null,
    "created": "Mon Jan 01 2024 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "life-itself",
    "tags": null,
    "url": "https://studio.lifeitself.org",
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/sensemaking-studio"
  },
  {
    "slug": "social-media",
    "type": "initiative",
    "file": "initiatives/social-media.md",
    "title": "Social Media",
    "description": "Life Itself social media presence and content across platforms.",
    "status": "active",
    "category": null,
    "created": "Wed Apr 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "code": null,
    "parent": "comms",
    "tags": [
      "lifeitself",
      "communications",
      "social-media"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "yoyo-pasieka",
    "sitePath": "/initiatives/social-media"
  },
  {
    "slug": "teal-estate",
    "type": "initiative",
    "file": "initiatives/teal-estate.md",
    "title": "Teal Estate",
    "description": "Real-estate strategy and tooling for conscious co-living and community projects.",
    "status": "paused",
    "category": null,
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "code": null,
    "parent": "developmental-spaces-dds",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null,
    "owner": "rufus-pollock",
    "sitePath": "/initiatives/teal-estate"
  }
];
